Личный проект: маршрут по тайным тропам
htmlacademy-react/845763-what-to-watch-5 pull request #4
Opened 2020-10-08 15:14 UTC by KupperXD

---
:mortar_board: [Личный проект: маршрут по тайным тропам](https://up.htmlacademy.ru/react/5/user/845763/tasks/7)

2020-10-09 05:22 UTC, klimnikova requested changes
Привет, по трем маршрутам не отрисовываются компоненты, там проблема в том, что пути к бандлам, стилям и картинкам надо подключать от корня. Если нужна будет помощь, обращайся)

2020-10-09 05:22 UTC, klimnikova commented on src/components/add-review/add-review.jsx
> +  return (<React.Fragment>
Просто комментарий по стилю, что лучше переносить на следующую строку после return JSX

2020-10-09 05:22 UTC, klimnikova commented on src/components/app/app.jsx
> +          </Home>
Тоже небольшой комментарий, что пустые компоненты обычно самозакрывающиеся, то есть <Home />

2020-10-09 05:22 UTC, klimnikova commented on src/components/film/film.jsx
> +                  {/* <use xlink:href="#add"></use> */}
Закомментированный код нужно убрать. Критерий Б31. Если проблема с атрибутом, то в React все свойства и атрибуты DOM (включая обработчики событий) должны быть в стиле camelCase, он будет работать как  `xlinkHref`

2020-10-09 05:22 UTC, klimnikova commented on src/components/player/player.jsx
> +              {/* <use xlink:href="#play-s"></use> */}
тоже закомментированный код

2020-10-09 05:22 UTC, klimnikova commented on src/components/player/player.jsx
> +            <div className="player__toggler" style="left: 30%;">Toggler</div>
Если ты хочешь добавить стили к элементу в JSX,  то делаем это в следующем виде `style={{marginRight: '3em'}}`. иначе, работать не будет

2020-10-09 05:22 UTC, klimnikova commented on src/components/app/app.jsx
> +        <Route path="/films/:id" exact>
по трем последним маршрутам не отрисовываются компонент

2020-10-10 09:26 UTC, KupperXD commented on src/components/player/player.jsx
> +            <div className="player__toggler" style="left: 30%;">Toggler</div>
Передаём объект, получается.

2020-10-10 09:28 UTC, KupperXD commented on src/components/app/app.jsx
> +        <Route path="/films/:id" exact>
С путём у бандла и правда чет накосячил.

2020-10-10 09:28 UTC, KupperXD commented on src/components/player/player.jsx
> +              {/* <use xlink:href="#play-s"></use> */}
Ругался сборщик, временно убрал, щас поправил на camelCase

2020-10-10 11:47 UTC, klimnikova approved these changes
Теперь все отлично. Молодец:+1:

2020-10-10 11:47 UTC, merged