Моки
htmlacademy-react/845763-what-to-watch-5 pull request #5
Opened 2020-10-20 21:34 UTC by KupperXD

2020-10-21 08:06 UTC, klimnikova requested changes
Запусти, пожалуйста, npm run eslint и фиксани все ошибки линтера. Маршрут films/:id - не открывается, там ошибка

2020-10-21 08:06 UTC, klimnikova commented on src/components/review-post/review-post.jsx
> +        evt.preventDefault();
проверила, какая приходит дата. У тебя там опечатка в названии полей. И рейтинг плохо проставляется
`rating: "5"
review-text: "eremkvm"
reviw-text: null`

2020-10-24 05:49 UTC, klimnikova requested changes
Делай, пожалуйста, перед каждой отправкой `npm run eslint`

2020-10-24 05:49 UTC, klimnikova commented on src/components/app/app.jsx
> +
вот этот роут лишний,  из-за него не отрабатывает роут правильно

2020-10-28 20:31 UTC, KupperXD commented
не совсем понимаю как фиксить ошибки, валидации пропсов в роутах, я ведь валидирую пропсы в компонентах. Мне внутри роута до компонента надо тоже как то валидировать ?

2020-10-29 01:51 UTC, klimnikova commented
Ты можешь props сразу передавать в компонент `(props) => <Player {...props} />`

2020-10-29 01:56 UTC, klimnikova commented
<img width="555" alt="Снимок экрана 2020-10-29 в 11 54 52" src="https://user-images.githubusercontent.com/48652022/97515841-a284a180-19dd-11eb-908e-36c8aae7e278.png">
Советую сделать вот так

2020-10-30 13:00 UTC, merged